/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import classes.Aluno;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author José Luan Silva do Nascimento, 20141064010220
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    HashMap<String, Aluno> alunos = new HashMap<>();
    public Visual() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            String abc = Visual.lerarq("alunos2.txt");
            String[] lista = abc.split("#");
            for (String lista1 : lista) {
                String[] lista2 = lista1.split(",");
                
                Aluno pessoa = new Aluno(mostrar(lista2[0]), mostrar(lista2[1]), mostrar(lista2[2]),Integer.parseInt(lista2[3]));        
                alunos.put(mostrar(lista2[0]), pessoa);
            }
        } catch (IOException io) {
            JOptionPane.showMessageDialog(this,"Exceção IO \n"+io.getMessage(), "___Exceção___", WIDTH);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnpesquisar = new javax.swing.JButton();
        btnatualizar = new javax.swing.JButton();
        btncadastrar = new javax.swing.JButton();
        btnremover = new javax.swing.JButton();
        tfturma = new javax.swing.JTextField();
        tfnome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfmatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlstrike = new javax.swing.JLabel();
        btzerar = new javax.swing.JButton();
        btadicionar = new javax.swing.JButton();
        jcconfirmar = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("logoscgrande.png")) );
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnpesquisar.setBackground(new java.awt.Color(0, 79, 63));
        btnpesquisar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnpesquisar.setForeground(new java.awt.Color(241, 255, 249));
        btnpesquisar.setText("Pesquisar");
        btnpesquisar.setBorder(null);
        btnpesquisar.setBorderPainted(false);
        btnpesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });

        btnatualizar.setBackground(new java.awt.Color(0, 79, 63));
        btnatualizar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnatualizar.setForeground(new java.awt.Color(241, 255, 249));
        btnatualizar.setText("Atualizar");
        btnatualizar.setBorder(null);
        btnatualizar.setBorderPainted(false);
        btnatualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizarActionPerformed(evt);
            }
        });

        btncadastrar.setBackground(new java.awt.Color(0, 79, 63));
        btncadastrar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btncadastrar.setForeground(new java.awt.Color(241, 255, 249));
        btncadastrar.setText("Cadastrar");
        btncadastrar.setBorder(null);
        btncadastrar.setBorderPainted(false);
        btncadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });

        btnremover.setBackground(new java.awt.Color(0, 79, 63));
        btnremover.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnremover.setForeground(new java.awt.Color(241, 255, 249));
        btnremover.setText("Remover");
        btnremover.setBorder(null);
        btnremover.setBorderPainted(false);
        btnremover.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoverActionPerformed(evt);
            }
        });

        tfturma.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        tfturma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(81, 185, 171), 1, true));

        tfnome.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        tfnome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(81, 185, 171), 1, true));
        tfnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(12, 142, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Matricula");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(12, 142, 125));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Turma");

        tfmatricula.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        tfmatricula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(81, 185, 171), 1, true));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(12, 142, 125));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 116, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CONTROLE DE FARDAMENTOS");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 116, 102), 2, true));

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(6, 116, 102));
        jLabel6.setText("STRIKE =");

        jlstrike.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jlstrike.setForeground(new java.awt.Color(6, 116, 102));
        jlstrike.setText("0");

        btzerar.setBackground(new java.awt.Color(0, 79, 63));
        btzerar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btzerar.setForeground(new java.awt.Color(241, 255, 249));
        btzerar.setText("ZERAR");
        btzerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btzerarActionPerformed(evt);
            }
        });

        btadicionar.setBackground(new java.awt.Color(0, 79, 63));
        btadicionar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btadicionar.setForeground(new java.awt.Color(241, 255, 249));
        btadicionar.setText("ADICIONAR");
        btadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlstrike)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btadicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btzerar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btadicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btzerar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jlstrike))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jcconfirmar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jcconfirmar.setForeground(new java.awt.Color(6, 116, 102));
        jcconfirmar.setText("Confirmar");
        jcconfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logoscgrande.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfturma, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcconfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnatualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnremover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfturma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnatualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnremover, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcconfirmar))))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarActionPerformed
        if (alunos.containsKey(tfmatricula.getText())) {
            Aluno al = (Aluno) alunos.get(tfmatricula.getText());
            tfnome.setText(al.getNome());
            tfturma.setText(al.getTurma());
            jlstrike.setText(""+al.getStrike());

            JOptionPane.showMessageDialog(this, "Aluno encontrado com sucesso!!!", "___Pesquisa___", WIDTH);

        }else{
            if (tfmatricula.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Digite a matricula do aluno!!!", "___Pesquisa___", WIDTH);
            }else{
                JOptionPane.showMessageDialog(this, "Matricula não registrada no sitema!!!", "___Pesquisa___", WIDTH);
            }
        }
    }//GEN-LAST:event_btnpesquisarActionPerformed

    private void btnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizarActionPerformed
        if (tfmatricula.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a matricula do aluno!!!", "___Pesquisa___", WIDTH);
        }
        if (alunos.containsKey(tfmatricula.getText())) {
            alunos.remove(tfmatricula.getText());
            Aluno aluno = new Aluno(tfmatricula.getText(), tfnome.getText(), tfturma.getText(),Integer.parseInt(jlstrike.getText()));
            alunos.put(tfmatricula.getText(), aluno);
            try {
                    String novamensagem = "";
                    String abc = Visual.lerarq("alunos2.txt");
                    String[] lista = abc.split("#");
                    for (String lista1 : lista) {
                        String[] lista2 = lista1.split(",");
                        if (mostrar(lista2[0]).equals(tfmatricula.getText())) {
                            String dados = esconder(tfmatricula.getText()) + "," + esconder(tfnome.getText()) + "," + esconder(tfturma.getText()) + "," + jlstrike.getText() + "#";
                            novamensagem += dados;
                        }else{
                            novamensagem += lista1+"#";
                        }
                    }
                    escreverarq("alunos2.txt", novamensagem);
                } catch (IOException io) {
                    JOptionPane.showMessageDialog(this,"Exceção IO \n"+io.getMessage(), "___Exceção___", WIDTH);
                }
            JOptionPane.showMessageDialog(this, "Aluno atualizado com sucesso!!!", "___Atualizado___", WIDTH);
        }
    }//GEN-LAST:event_btnatualizarActionPerformed

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        if (tfmatricula.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a matricula do aluno!!!", "___Pesquisa___", WIDTH);
        }
        if (!alunos.containsKey(tfmatricula.getText())) {
        try {
            
            if (!tfmatricula.getText().equals("")) {
                Aluno aluno = new Aluno(Integer.parseInt(tfmatricula.getText())+"", tfnome.getText(), tfturma.getText(),Integer.parseInt(jlstrike.getText()));
                alunos.put(tfmatricula.getText(), aluno);
                String dadoaluno = esconder(tfmatricula.getText()) + "," + esconder(tfnome.getText()) + "," + esconder(tfturma.getText())  + ","+ jlstrike.getText() +"#\n";

                String textoantigo = lerarq("alunos2.txt");
                escreverarq("alunos2.txt", textoantigo + dadoaluno);

                JOptionPane.showMessageDialog(this, "Aluno salvo com sucesso!!!", "___Cadastro___", WIDTH);
            }
            

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Exceção " + e.getMessage() + "\n"
                    + "digte uma matricula válida", "___Exceção___", WIDTH);
        } catch (IOException ex) {
            Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
        }
        } else {
            JOptionPane.showMessageDialog(this, "Matricula ja está cadastrada no sistema!!!", "___Cadastro___", WIDTH);
        }
    }//GEN-LAST:event_btncadastrarActionPerformed

    private void btnremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoverActionPerformed
        
        if (jcconfirmar.isSelected()) {
            if (tfmatricula.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Digite a matricula do aluno!!!", "___Pesquisa___", WIDTH);
            }
            if (alunos.containsKey(tfmatricula.getText())) {
            alunos.remove(tfmatricula.getText());
            
            try {
                    String novamensagem = "";
                    String abc = Visual.lerarq("alunos2.txt");
                    String[] lista = abc.split("#");
                    
                    for (String lista1 : lista) {
                        String[] lista2 = lista1.split(",");
                        if (!mostrar(lista2[0]).equals(tfmatricula.getText())) { 
                            novamensagem += lista1+"#";
                        }
                    }
                    escreverarq("alunos2.txt", novamensagem);
                    System.out.println(novamensagem);
                    System.out.println("ok!!!!!!!!!!!!");
            }catch (IOException io) {
                    JOptionPane.showMessageDialog(this,"Exceção IO \n"+io.getMessage(), "___Exceção___", WIDTH);
            }
            JOptionPane.showMessageDialog(this, "Aluno foi removido com sucesso!!!", "___Remoção___", WIDTH);
            jcconfirmar.setSelected(false);
            tfmatricula.setText("");
            tfnome.setText("");
            tfturma.setText("");
            jlstrike.setText("0");

        }
    }else{
            JOptionPane.showMessageDialog(this,"Por favor selecione o check box(confirmar)!!!", "___Remover___", WIDTH);
        }
    }//GEN-LAST:event_btnremoverActionPerformed

    private void tfnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnomeActionPerformed

    private void btzerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btzerarActionPerformed
        if (tfmatricula.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a matricula do aluno!!!", "___Pesquisa___", WIDTH);
        }
        if (alunos.containsKey(tfmatricula.getText())) {
            jlstrike.setText("0");
            Aluno aluno = alunos.get(tfmatricula.getText());
            aluno.zerarStrike();
            alunos.remove(tfmatricula.getText());
            alunos.put(tfmatricula.getText(), aluno);
            try {
                String novamensagem = "";
                String abc = Visual.lerarq("alunos2.txt");
                String[] lista = abc.split("#");
                for (String lista1 : lista) {
                    String[] lista2 = lista1.split(",");
                    if (mostrar(lista2[0]).equals(tfmatricula.getText())) {
                        lista1 = lista2[0] + "," + lista2[1] + "," + lista2[2] + "," + "0" + "#";
                        novamensagem += lista1;
                    }else{
                     novamensagem += lista1+"#";
                    }
                }
                escreverarq("alunos2.txt", novamensagem);
            } catch (IOException io) {
                JOptionPane.showMessageDialog(this,"Exceção IO \n"+io.getMessage(), "___Exceção___", WIDTH);
            }
            
        }
    }//GEN-LAST:event_btzerarActionPerformed

    private void btadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadicionarActionPerformed
        if (tfmatricula.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a matricula do aluno!!!", "___Pesquisa___", WIDTH);
        }
        if (alunos.containsKey(tfmatricula.getText())) {
            Aluno aluno = alunos.get(tfmatricula.getText());
            if (aluno.getStrike() < 3) {
                aluno.setStrike();
                jlstrike.setText(aluno.getStrike()+"");
                alunos.remove(tfmatricula.getText());
                alunos.put(tfmatricula.getText(), aluno);
                try {
                    String novamensagem = "";
                    String abc = Visual.lerarq("alunos2.txt");
                    String[] lista = abc.split("#");
                    for (String lista1 : lista) {
                        String[] lista2 = lista1.split(",");
                        if (mostrar(lista2[0]).equals(tfmatricula.getText())) {
                            lista1 = lista2[0] + "," + lista2[1]+ "," + lista2[2]+ "," + jlstrike.getText() + "#";
                            novamensagem += lista1;
                        }else{
                            novamensagem += lista1+"#";
                        }
                    }
                    escreverarq("alunos2.txt", novamensagem);
                } catch (IOException io) {
                    JOptionPane.showMessageDialog(this,"Exceção IO \n"+io.getMessage(), "___Exceção___", WIDTH);
                }
            }else{
                JOptionPane.showMessageDialog(this,"O aluno já está com o máximo de strikes", "___Strikes___", WIDTH);
            }
        }
    }//GEN-LAST:event_btadicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Visual().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadicionar;
    private javax.swing.JButton btnatualizar;
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton btnpesquisar;
    private javax.swing.JButton btnremover;
    private javax.swing.JButton btzerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jcconfirmar;
    private javax.swing.JLabel jlstrike;
    private javax.swing.JTextField tfmatricula;
    private javax.swing.JTextField tfnome;
    private javax.swing.JTextField tfturma;
    // End of variables declaration//GEN-END:variables

    public static String lerarq(String caminho) throws IOException {
        String texto = "";
        String src;
        File arquivo = new File(caminho);
        BufferedReader in = new BufferedReader(new FileReader(arquivo));
        while ((src = in.readLine()) != null) {
            texto += src;
        }
        in.close();
        return texto;
    }

    public static void escreverarq(String caminho, String texto) throws IOException {

        File arquivo = new File(caminho);
        try (PrintWriter pwriter = new PrintWriter(arquivo)) {
            pwriter.write(texto + "\n");
            pwriter.close();
        }
    }
    public static String esconder(String mensagem){

        String resultado = "";
        for (int i = 0; i < mensagem.length(); i++) {
            int temp = mensagem.charAt(i);

            resultado += (char) (temp+13);
        }
        return resultado;
    }
    public static String mostrar(String mensagem){

        String resultado = "";
        for (int i = 0; i < mensagem.length(); i++) {
            int temp = mensagem.charAt(i);
            resultado += (char) (temp-13);
        }
        return resultado;

    }
}
